# Generated by Django 3.2.4 on 2021-07-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('knowledge', models.IntegerField(max_length=3)),
            ],
            options={
                'db_table': 'Languages',
            },
        ),
    ]
