# Generated by Django 3.2.4 on 2021-07-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='knowledge',
            field=models.IntegerField(),
        ),
    ]
