# Generated by Django 3.2.4 on 2021-07-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_languages_knowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images/projects')),
                ('url', models.CharField(blank=True, max_length=50)),
                ('repo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Projects',
            },
        ),
    ]
